name: openlist_viewer
description: A WebDAV based file manager with media capabilities using Material 3.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.2

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # UI & Routing
  go_router: ^14.0.0
  google_fonts: ^6.1.0
  
  # Network & Protocol
  webdav_client: ^1.2.0
  dio: ^5.4.0 # 用于可能的 API 调用 (获取权限组)

  # Storage
  flutter_secure_storage: ^9.0.0 # 保存密码
  shared_preferences: ^2.2.2 # 保存非敏感配置 (如历史 URL)

  # Media Player (libmpv based)
  fvp: ^0.35.2 
  video_player: ^2.8.2

  # Image & PDF
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  flutter_pdfview: ^1.3.2

  # Util
  intl: ^0.20.2
  path: ^1.9.0
  chewie: ^1.13.0
  video_thumbnail: ^0.5.6
  path_provider: ^2.1.5
  flutter_colorpicker: ^1.1.0
  http: ^1.6.0
  lpinyin: ^2.0.3
  connectivity_plus: ^7.0.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  open_filex: ^4.7.0
  flutter_local_notifications: ^20.0.0
  uuid: ^4.5.2
  android_intent_plus: ^6.0.0
  flutter_volume_controller: ^1.3.4
  screen_brightness: ^2.1.7
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
